### ISSUE TITLE
[BUILD FAILURE] Solution fails to build with 992 errors

### ISSUE THREAD

**Issue by headsetguy37** [jte/installscript-decompiler#1]
I am using Visual Studio 2019. I have tried re-targeting the solution, as suggested when I open it, but when I attempt to build the solution, it fails with 992 errors. Looking through the errors, it seems that some lines were using the incorrect namespace ("is not a member of 'std'" in particular shows up a lot). Maybe a header was not included? Also, the project seems to be incomplete; the solution is expecting a project called "Compiler.vcxproj".

-Johnny

**Comment by bobo2050** [comment]
you need add the head file <iostream.h>

**Comment by jte** [comment]
A large refactoring has been undertook. It now builds clean.
